name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        env:
          LIBLAB_ENVIRONMENT: ${{ secrets.LIBLAB_ENVIRONMENT }}
        uses: ./
        with:
          liblab_token: ${{ secrets.LIBLAB_TOKEN }}
          liblab_github_token: ${{ secrets.LIBLAB_GITHUB_TOKEN }}

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.status }}"
